package com.vitisoft.backend.model;

import com.fasterxml.jackson.annotation.JsonFormat;
import com.fasterxml.jackson.annotation.JsonProperty;

import java.time.OffsetDateTime;

public class Emergency {

    @JsonProperty("id")
    public int id;

    @JsonProperty("userName")
    public String userName;

    // Accepts ISO 8601 with milliseconds and timezone, e.g.
    // 2025-06-02T03:26:17.677Z
    @JsonProperty("receivedTime")
    @JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "yyyy-MM-dd'T'HH:mm:ss.SSSX")
    public OffsetDateTime receivedTime;

    @JsonProperty("callerID")
    public String callerID;

    @JsonProperty("details")
    public String details;

    @JsonProperty("address")
    public String address;

    @JsonProperty("type")
    public String type;

    @JsonProperty("isActive")
    public boolean isActive;

    @JsonProperty("priority")
    public int priority;

    // Required no-argument constructor for JSON deserialization
    public Emergency() {
    }

    // Constructor for new emergencies (ID auto-generated by DB)
    public Emergency(String userName, OffsetDateTime receivedTime,
            String callerID, String details, String address,
            String type, boolean isActive, int priority) {
        this.userName = userName;
        this.receivedTime = receivedTime;
        this.callerID = callerID;
        this.details = details;
        this.address = address;
        this.type = type;
        this.isActive = isActive;
        this.priority = priority;
    }

    // Constructor for emergencies loaded from DB (with ID)
    public Emergency(int id, String userName, OffsetDateTime receivedTime,
            String callerID, String details, String address,
            String type, boolean isActive, int priority) {
        this.id = id;
        this.userName = userName;
        this.receivedTime = receivedTime;
        this.callerID = callerID;
        this.details = details;
        this.address = address;
        this.type = type;
        this.isActive = isActive;
        this.priority = priority;
    }
}